---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd
  run_command: /lib/systemd/systemd
  hostname: salt-formula.ci.local
  require_chef_omnibus: false  

# verifier:
  # name: inspec

platforms:
  - name: ubuntu-18.04
  - name: debian-9
  - name: centos-7

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_pillar_root: pillar.example
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: tomcat
  state_top:
    base:
      '*':
        - tomcat
suites:
  - name: tomcat_install
    provisioner:
      state_top:
        base:
          '*':
            - tomcat
            - tomcat.native
            - tomcat.config

  - name: tomcat_extend
    provisioner:
      state_top:
        base:
          '*':
            - tomcat.manager
            - tomcat.vhosts
            - tomcat.expires
            - tomcat.context
            - tomcat.cluster
