language: ruby

rvm:
  - 2.2.5

sudo: required
services: 
  - docker

env:
  matrix:
  - INSTANCE: install-ubuntu-1804
  - INSTANCE: install-centos-7   
  - INSTANCE: install-debian-9
  - INSTANCE: config-ubuntu-1804 
  - INSTANCE: config-centos-7    
  - INSTANCE: config-debian-9
  - INSTANCE: native-ubuntu-1804 
  - INSTANCE: native-centos-7    
  - INSTANCE: manager-ubuntu-1804
  - INSTANCE: manager-centos-7   
  - INSTANCE: expires-ubuntu-1804
  - INSTANCE: expires-centos-7   
  - INSTANCE: context-ubuntu-1804
  - INSTANCE: context-centos-7   
  - INSTANCE: cluster-ubuntu-1804
  - INSTANCE: cluster-centos-7

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

install:
  # setup ci for test formula
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install

script: bundle exec kitchen verify ${INSTANCE}
